#!/bin/bash

cd /var/www/mediawiki

# Move generic config out of place or installer wont run
mv ./LocalSettings.php /tmp/LocalSettings.php

# Run installer
php maintenance/install.php Wiki $1 --pass=$2 \
 --dbport=${MEDIAWIKI_DB_PORT} \
 --dbserver=${MEDIAWIKI_DB_HOST} \
 --dbtype=${MEDIAWIKI_DB_TYPE} \
 --dbname=${MEDIAWIKI_DB_NAME} \
 --dbprefix=${MEDIAWIKI_DB_PREFIX} \
 --installdbuser=${MEDIAWIKI_DB_USER} \
 --installdbpass=${MEDIAWIKI_DB_PASSWORD} \
 --dbuser=${MEDIAWIKI_DB_USER} \
 --dbpass=${MEDIAWIKI_DB_PASSWORD} \
 --scriptpath=/

# Fix SQLite data folder permissions
chown -R www-data:www-data /data

# Display random generated secret key
echo ""
grep '$wgSecret' LocalSettings.php

# Remove config generated by the installer
rm -rf ./LocalSettings.php

# Restore generic config
mv /tmp/LocalSettings.php ./LocalSettings.php
